### ISSUE TITLE
There was an error: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by GHXST01** [matiasb/unpy2exe#3]
I'm trying to unpack a python generated .exe
However when using unpy2exe I keep getting:
`There was an error: 'NoneType' object has no attribute 'data'`

What makes it throw this error?

**Comment by Zolomon** [comment]
Hi @GHXST01 and @matiasb ,

I am also receiving the same error as above. @GHXST01 , did you manage to solve it?

**Comment by matiasb** [comment]
Hi,
Do you have a sample .exe I can take a look at? Also, which Python version are you running?
Thanks.

**Comment by notvelleda** [comment]
I'm having this problem too

**Comment by tennc** [comment]
` python unpy2exe -o 123 "d:\b.exe"
There was an error: 'NoneType' object has no attribute 'data'`

`C:\python27-x64\Scripts
λ "C:\python27-x64\python.exe" unpy2exe -o 123  "d:\b.exe"
There was an error: 'NoneType' object has no attribute 'data'`

I'm having this problem too
  python3 && python2

**Comment by b2az** [comment]
Same. Whats happening here?

**Comment by matiasb** [comment]
Finally I got someone to send me an executable to reproduce this. It seems this issue is raised for example when trying `unpy2exe` with a pyinstaller python executable, which won't work. The only executables the tool handles (at least for now) are the ones created using py2exe.

In any case, added an extra check to ensure the executable matches the py2exe expected format (https://github.com/matiasb/unpy2exe/commit/06d849341734e8f485873be52c8aed5048573e9c).

On the other hand, if you are dealing with a pyinstaller executable maybe you can try with:
https://sourceforge.net/projects/pyinstallerextractor/
